version: '3'
volumes:
  dados:
services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      # volume dos dados
      - ./postgres_data:/var/lib/postgresql/data
      # scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend:
    image: nginx:1.13
    volumes:
      # página web
      - ./web:/usr/share/nginx/html/
      # configuração proxy reverso
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  app:
    image: python:3.6
    volumes:
      # Aplicação
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
  queue:
    image: redis:3.2
  worker:
    image: python:3.6
    volumes:
      # worker
      - ./worker:/worker
    working_dir: /worker
    command: bash ./work.sh
    